import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";

import { Manrope as ManropeFont } from "next/font/google";
import "./globals.css";

const manrope = ManropeFont({
  weight: ["400", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={manrope.className}>
        <Header />
        {children}

        <Footer />
      </body>
    </html>
  );
}
